Repository inland-empire-software-development/main, pull requests merged in 2019-11, with the labels that each got.

#108 Pulling master down to dev tier
  pages/index.js
  pages/page.js
  pages/post.js
  sass/components/_announcements.scss
  sass/components/global/_announcement.scss
  sass/components/global/_navigation.scss
  sass/index.scss
  sass/pages/_page.scss
  src/components/footer.js
  src/components/global/Announcement.js
  src/components/global/Footer.js
  src/components/global/Nav.js
  static/images/headers/page-header.jpg
  yarn.lock
Labels: parity

#104 Feature - External links should open in a new tab for navigation
  src/components/global/Nav.js
Labels: enhancement, tweaks

#102 Update mission and goal component to pull data from IESD API
  sass/components/layout/_goals.scss
  sass/components/layout/_mission.scss
  src/components/footer.js
  src/components/layout/Goals.js
  src/components/layout/Mission.js
Labels: enhancement

#111 Pulling master down to dev
  sass/components/layout/_goals.scss
  sass/components/layout/_mission.scss
  src/components/footer.js
  src/components/global/Nav.js
  src/components/layout/Goals.js
  src/components/layout/Mission.js
  yarn.lock
Labels: parity

#115 #106 - Fix for linting errors
  .eslintignore
  lib/init-apollo.js
  lib/with-apollo-client.js
  pages/_app.js
  src/components/SingleEvent.js
  src/components/layout/Community.js
  static/images/desktop/iesd-bg-light.jpg
Labels: enhancement

#123 Pulling master down to dev for parity
  sass/components/global/_navigation.scss
  sass/components/layout/_story.scss
  src/components/MemberList.js
  src/components/global/Nav.js
  src/components/layout/Blog.js
  src/components/layout/Community.js
  src/components/layout/Story.js
  yarn.lock
Labels: parity

#130 only mobile nav items should toggle visibility of navigation
  src/components/global/Nav.js
Labels: hotfix

#131 Pulling master down the tiers for parity
  src/components/global/Nav.js
Labels: parity

#133 Loader component - testing on dev
  pages/_document.js
  pages/index.js
  pages/post.js
  public/favicon.ico
  public/static/images/join-section-background.jpg
  public/static/images/loader.gif
  public/static/images/loader.svg
  sass/components/global/_loader.scss
  sass/index.scss
  src/components/global/Loader.js
  src/components/layout/Blog.js
  src/components/layout/Operations.js
  src/components/layout/Speakers.js
  src/components/layout/Sponsors.js
  src/components/layout/Story.js
Labels: testing
