Repository inland-empire-software-development/main, pull requests merged in 2019-12, with the labels that each got.

#147 Pushing update up the tiers - mentorship page
  .eslintrc
  pages/_app.js
  pages/forms/mentor.js
  pages/forms/mentorship.js
  pages/index.js
  pages/mentorship.js
  pages/page.js
  pages/post.js
  sass/base/_global.scss
  sass/base/_typography.scss
  sass/components/_mentorship.scss
  sass/components/_pageTitle.scss
  sass/components/global/_button.scss
  sass/components/layout/_goals.scss
  sass/components/layout/_mission.scss
  sass/index.scss
  sass/pages/_index.scss
  sass/pages/_mentorship.scss
  src/components/Blog.js
  src/components/Community.js
  src/components/Goals.js
  src/components/Hero.js
  src/components/Mentorships.js
  src/components/Mission.js
  src/components/Operations.js
  src/components/PageTitle.js
  src/components/Slogan.js
  src/components/Speakers.js
  src/components/Sponsors.js
  src/components/Story.js
  src/components/global/Footer.js
  src/components/global/Nav.js
  src/components/layout/Community.js
  yarn.lock
Labels: enhancement, parity

#148 Mentorship update
  .eslintrc
  pages/_app.js
  pages/forms/mentor.js
  pages/forms/mentorship.js
  pages/index.js
  pages/mentorship.js
  pages/page.js
  pages/post.js
  sass/base/_global.scss
  sass/base/_typography.scss
  sass/components/_mentorship.scss
  sass/components/_pageTitle.scss
  sass/components/global/_button.scss
  sass/components/layout/_goals.scss
  sass/components/layout/_mission.scss
  sass/index.scss
  sass/pages/_index.scss
  sass/pages/_mentorship.scss
  src/components/Blog.js
  src/components/Community.js
  src/components/Goals.js
  src/components/Hero.js
  src/components/Mentorships.js
  src/components/Mission.js
  src/components/Operations.js
  src/components/PageTitle.js
  src/components/Slogan.js
  src/components/Speakers.js
  src/components/Sponsors.js
  src/components/Story.js
  src/components/global/Footer.js
  src/components/global/Nav.js
  yarn.lock
Labels: approved, enhancement

#156 Pulling master down the tiers for parity
  pages/index.js
  public/static/images/desktop/goals-bg.jpg
  sass/components/global/_announcement.scss
  sass/components/layout/_blog.scss
  sass/components/layout/_goals.scss
  sass/components/layout/_hero.scss
  src/components/About.js
  src/components/Blog.js
  src/components/Community.js
  src/components/Goals.js
  src/components/Mission.js
  src/components/Operations.js
  src/components/Speakers.js
  src/components/global/Nav.js
Labels: parity

#157 Pulling master down the tiers to dev
  pages/index.js
  public/static/images/desktop/goals-bg.jpg
  sass/components/global/_announcement.scss
  sass/components/layout/_blog.scss
  sass/components/layout/_goals.scss
  sass/components/layout/_hero.scss
  src/components/About.js
  src/components/Blog.js
  src/components/Community.js
  src/components/Goals.js
  src/components/Mission.js
  src/components/Operations.js
  src/components/Speakers.js
  src/components/global/Nav.js
Labels: parity

#164 bettered img quality, took off saturation.
  sass/components/layout/_community.scss
  src/components/Community.js
Labels: tweaks
